#!/bin/bash

# this script is used to configure security

function configure_security {
    # to disabled the selinux
    setenforce 0
    # to disabled the iptables
    iptables -F
    service iptables stop
    chkconfig iptables off
}